spring:
  profiles:
    active: local
    #active: test
    #active: prod
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  # 时间类型格式化，时区为 +8区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    aop:
      proxy-target-class: true
  jmx:
    default:
      domain: sifang
# 日志配置
#logging:
#  level:
#    com.sifang: debug
#    org.springframework: warn
server:
  session:
    timeout: 6000
  tomcat:
    uri-encoding: UTF-8
    max-threads: 3000
    max-connections: 6000
  servlet:
    context-path: /api

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  type-aliases-package: com.sifang.bussiness.dao.table
map:
  tele:
    url: 5043907698:AAE_xfC77Eqz_FawBOW4fauebnhD35q2Q7U